import Head from "next/head";
import Image from "next/image";
import { Blog } from "src/components/sections/Blog";
import { Clients } from "src/components/sections/Clients";
import { Contact } from "src/components/sections/Contact";
import { Header } from "src/components/sections/Header";
import { Hero } from "src/components/sections/Hero";
import { Hire } from "src/components/sections/Hire";
import { Navbar } from "src/components/sections/Navbar";
import { Numbers } from "src/components/sections/Numbers";
import { Portfolio } from "src/components/sections/Portfolio";
import { Resume } from "src/components/sections/Resume";
import { Services } from "src/components/sections/Services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Huascar.one</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossOrigin="anonymous"
        />

        <link
          href="https://fonts.googleapis.com/css?family=Muli:200,300,400,600,700,,800,900|Josefin+Sans:300,400,600,700"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="css/font-awesome.min.css" />
        <link rel="stylesheet" href="css/style.css" />
        <link rel="stylesheet" href="css/owl.carousel.min.css" />
        <link rel="stylesheet" href="css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="css/magnific-popup.css" />
        <link rel="stylesheet" href="css/et-line.css" />
        <link
          rel="stylesheet"
          type="text/css"
          href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
        />
        <script src="js/html5shiv.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
        <script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
          integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
          crossOrigin="anonymous"
        ></script>
        <script src="js/scrollIt.min.js"></script>
        <script src="js/jquery.magnific-popup.min.js"></script>
        <script src="js/owl.carousel.min.js"></script>
        <script src="js/jquery.stellar.min.js"></script>
        <script src="js/typed.js"></script>
        <script src="js/jquery.waypoints.min.js"></script>
        <script src="js/jquery.counterup.min.js"></script>
        <script src="js/isotope.pkgd.min.js"></script>
        <script src="js/particles.min.js"></script>
        <script src="js/app.js"></script>
        <script src="js/validator.js"></script>
        <script src="js/custom.js"></script>
      </Head>
      {/* <div className="loading">
        <div className="load-circle"></div>
      </div>

      <div className="button-top" data-scroll-nav="0">
        <span>
          <i className="fa fa-angle-up" aria-hidden="true"></i>
        </span>
      </div> */}
      <Navbar />
      <Header />
      <Hero />
      <Resume />
      <Numbers />
      <Services />
      <Clients />
      <Portfolio />
      <Hire />
      <Blog />
      <Contact />
    </>
  );
}
